String JSONPLACEHOLDER_BASE_URL = "https://jsonplaceholder.typicode.com";
String SINGLE_POST_ENDPOINT = "/posts/1";
String MULTIPLE_POST_ENDPOINT = "/posts";
String PHOTOS_BASE_URL = "";
String QUERY_PARAMS = "";

String SINGLE_POST_API = JSONPLACEHOLDER_BASE_URL + SINGLE_POST_ENDPOINT;
String MULTIPLE_POST_API = JSONPLACEHOLDER_BASE_URL + MULTIPLE_POST_ENDPOINT;
String PHOTOS_API = PHOTOS_BASE_URL + QUERY_PARAMS;
